version: 2

project_name: filebrowser-ng

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/realalexandergeorgiev/filebrowser-ng/version.Version={{ .Version }} -X github.com/realalexandergeorgiev/filebrowser-ng/version.CommitSHA={{ .ShortCommit }}
    main: main.go
    binary: filebrowser-ng
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      # Experimental, may not work properly
      - goos: openbsd
        goarch: riscv64
      # Broken as of Go 1.24, deprecated as of Go 1.26
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

dockers:
  # Alpine docker images
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-amd64"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-arm64"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v6"
    goos: linux
    goarch: arm
    goarm: "6"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-armv6"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-armv6"
    extra_files:
      - docker
  - dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm/v7"
    goos: linux
    goarch: arm
    goarm: "7"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-armv7"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-armv7"
    extra_files:
      - docker

  ## s6-overlay docker images
  - dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64-s6"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-amd64-s6"
    extra_files:
      - docker
  - dockerfile: Dockerfile.s6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64-s6"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-arm64-s6"
    extra_files:
      - docker

docker_manifests:
  - name_template: "realalexandergeorgiev/filebrowser-ng:latest"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-armv7"
  - name_template: "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-armv7"
  - name_template: "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-amd64"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-arm64"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-armv7"
  ## s6 image manifests
  - name_template: "realalexandergeorgiev/filebrowser-ng:s6"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64-s6"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64-s6"
  - name_template: "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-s6"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-amd64-s6"
      - "realalexandergeorgiev/filebrowser-ng:{{ .Tag }}-arm64-s6"
  - name_template: "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-s6"
    image_templates:
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-amd64-s6"
      - "realalexandergeorgiev/filebrowser-ng:v{{ .Major }}-arm64-s6"

